# Generated by Django 5.1.4 on 2025-01-18 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_wordbank'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordbank',
            name='user',
        ),
        migrations.AddField(
            model_name='wordbank',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wordbank', to=settings.AUTH_USER_MODEL),
        ),
    ]
